# This workflow will build a Java project with Maven and run jpackage tool to package compiled application

name: JPackage Workflow

on:
 push:
    branches:
      - refactor

jobs:
  jpackage:
    name: Build Job
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Package with Maven
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        run: mvn -B package -Drevision="0.1.4" --file pom.xml

      - name: Run jpackage tool
        run: |
          jpackage --dest release --add-launcher DMK=jpackage.properties "@jpackage-${{ matrix.os }}.txt"

      - name: List created packages
        run: |
          ls release
